# See config.example.yml for documentation.
object_base: orig/GCBE7D
object: sys/main.dol
hash: 0123456789abcdef0123456789abcdef01234567
symbols: config/GCBE7D/symbols.txt
splits: config/GCBE7D/splits.txt
# Change this to match the linker version.
# See config.example.yml for a list.
mw_comment_version: 11
